### ISSUE TITLE
XNOR/bitcount operations not yet implemented?

### ISSUE THREAD

**Issue by Rahim16** [gplhegde/theano-xnor-net#1]
Hello,
I can see that the implementation is using lasagne's convolution operation. Any plans on adding XNOR/bitcount operations?
Also would be interested to receive pre-trained models for all three datasets.
Thank you for sharing the source code!
BR,
Rahim

**Comment by gplhegde** [comment]
Hi Rahim, this work is not targetted towards final deployment. Hence I did not implement bitcount based convolution. Since my goal was to target these networks for resource constrained systems, I thought that anyway we are not going to run Python based implementation. The deployment code is supposed to implement the xnor-bitcount convolution which may be specific for a particular CPU architecture. Hence, I don't have any plans to implement that here. However, I have plans for deployment code as a separate project, but that is going to take some time. 
You can find the trained model for all 3 dataset [here](https://drive.google.com/drive/folders/0B61XNQX1VsbPRTVFVnpqUHdwT1U?usp=sharing)

Thanks
Gopal
