### ISSUE TITLE
Performance of XNOR-Net

### ISSUE THREAD

**Issue by OpenBanboo** [gplhegde/theano-xnor-net#4]
Hi,

In the XNOR-Net paper, the author claims the speed up while running the inference. However, I try the codes provided here with MNIST and CIFAR10. On both datasets, the fixed-point mode takes longer time than float-point mode. For example, predicting 10000 pics in CIFAR10 through test, the test time of fixed-point is 357s while float-point is 271s. Could you please explain a bit about this results?

Best regards,
Fang

**Comment by gplhegde** [comment]
I just simulated fixed point mode here. Means, simulated all rounding errors. Everything here is in float.

**Comment by OpenBanboo** [comment]
I see, so no matter I pass --fixed or --float in, it uses float now?

**Comment by gplhegde** [comment]
--fixed will simulate fixed point to induce quantization effects. Means, if you have a number 1.32 and you want to use 2 factional bits, then this will perform 1.32 * 4 = 5.28 --> convert to int --> 5 --> convert back to float --> 5/4 = 1.25. Now you have 1.25 instead of 1.32 thus inducing fixed point effect. All this is to check how much accuracy drops for different fixed point precisions. Hope it helps. Take a look at [this](https://github.com/gplhegde/theano-xnor-net/blob/master/test/fxp_helper.py#L38)
